version: 2
updates:
  # Dependências Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
    reviewers:
      - "cleiton"  # Substitua pelo seu username do GitHub
    assignees:
      - "cleiton"  # Substitua pelo seu username do GitHub
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    ignore:
      # Ignorar atualizações major de pacotes críticos que podem quebrar
      - dependency-name: "fastapi"
        update-types: ["version-update:semver-major"]
      - dependency-name: "pydantic"
        update-types: ["version-update:semver-major"]
      - dependency-name: "pytest"
        update-types: ["version-update:semver-major"]
    groups:
      # Agrupar atualizações relacionadas
      fastapi-ecosystem:
        patterns:
          - "fastapi*"
          - "starlette*"
          - "uvicorn*"
      testing-tools:
        patterns:
          - "pytest*"
          - "coverage*"
          - "mock*"
      development-tools:
        patterns:
          - "black*"
          - "ruff*"
          - "mypy*"
          - "pre-commit*"

  # Dependências Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    reviewers:
      - "cleiton"
    assignees:
      - "cleiton"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    reviewers:
      - "cleiton"
    assignees:
      - "cleiton"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci/cd"